### PR TITLE
Quick grammar fix

### PR DESCRIPTION
**Pull request by LogerGrunt**
Just a quick grammar fix)

### CODE REVIEW

**Review by sametaor — APPROVED** [review]
Hey there! Thanks for the small contribution! I'm currently inactive with this project as I cannot find a proper bot hoster for a reasonable price, but I appreciate your contribution :)

**Comment by sametaor** [comment]
Closing this as I added the changes from my side. One thing I noticed is that you seem to be trying to fork a lot of discord bot repos while also "correcting" their mistakes, may I know why? If you would like to disclose it that is

**Comment by LogerGrunt** [comment]
> Closing this as I added the changes from my side. One thing I noticed is that you seem to be trying to fork a lot of discord bot repos while also "correcting" their mistakes, may I know why? If you would like to disclose it that is

Honestly just getting started on using github so I thought that contributing to some small projects is a way to get started

**Comment by sametaor** [comment]
Oh alright, that's fine by me. Feel free to contribute anytime, sorry about not taking in first prs but that's how I do it for prs made for the first time. Hope it's fine by you

**Comment by sametaor** [comment]
I would also love to see how you refine my old code in your way, as I have a lot of stuff in issues to be resolved as well, but just haven't gotten apt time and a good bot hoster yet to continue.

**Pull request merged**
